"""Planetary Body and Mission Registry for VEDA.

Maintains authoritative physical constants, atmospheric properties, and
spacecraft mission definitions across NASA, ESA, JAXA, and NOAA planetary programs.
"""
from __future__ import annotations

from typing import Dict, List, Optional
from .models import BodyInfo, InstrumentInfo, MissionInfo


# ===========================================================================
# PLANETARY BODIES & CELESTIAL TARGETS
# ===========================================================================

BODIES: Dict[str, BodyInfo] = {
    "venus": BodyInfo(
        id="venus",
        name="Venus",
        category="terrestrial_planet",
        radius_km=6051.8,
        surface_gravity=8.87,
        mean_molecular_weight=43.45,  # 96.5% CO2, 3.5% N2
        gas_constant_r=191.4,         # J / (kg K)
        isobaric_heat_capacity_cp=850.0,
        reference_pressure_hpa=92000.0,  # ~92 bar surface pressure
        atmospheric_composition={"CO2": 96.5, "N2": 3.5, "SO2": 0.015},
        description="Terrestrial planet with a massive, superrotating CO2 atmosphere, dense sulphuric acid cloud decks, and runaway greenhouse effect.",
        supported_missions=["akatsuki", "vex", "magellan", "pvo", "bepicolombo"],
    ),
    "mars": BodyInfo(
        id="mars",
        name="Mars",
        category="terrestrial_planet",
        radius_km=3389.5,
        surface_gravity=3.72,
        mean_molecular_weight=43.34,  # 95% CO2, 2.6% N2, 1.9% Ar
        gas_constant_r=191.8,
        isobaric_heat_capacity_cp=830.0,
        reference_pressure_hpa=6.1,  # ~6.1 hPa (610 Pa) surface pressure
        atmospheric_composition={"CO2": 95.32, "N2": 2.6, "Ar": 1.9, "O2": 0.13},
        description="Thin CO2 atmosphere with extensive seasonal polar cycling, dust storms, and ionospheric photo-chemical escape.",
        supported_missions=["maven", "mro"],
    ),
    "jupiter": BodyInfo(
        id="jupiter",
        name="Jupiter",
        category="gas_giant",
        radius_km=69911.0,
        surface_gravity=24.79,
        mean_molecular_weight=2.22,  # 89% H2, 10% He
        gas_constant_r=3745.0,
        isobaric_heat_capacity_cp=12360.0,
        reference_pressure_hpa=1000.0,  # 1 bar reference level
        atmospheric_composition={"H2": 89.8, "He": 10.2, "CH4": 0.3},
        description="Largest planet in solar system; deep hydrogen-helium atmosphere with prominent zonal jet streams and Great Red Spot.",
        supported_missions=["juno", "galileo", "cassini", "new_horizons"],
    ),
    "saturn": BodyInfo(
        id="saturn",
        name="Saturn",
        category="gas_giant",
        radius_km=58232.0,
        surface_gravity=10.44,
        mean_molecular_weight=2.07,  # 96% H2, 3% He
        gas_constant_r=4016.0,
        isobaric_heat_capacity_cp=14000.0,
        reference_pressure_hpa=1000.0,  # 1 bar reference level
        atmospheric_composition={"H2": 96.3, "He": 3.25, "CH4": 0.45},
        description="Ringed gas giant with high-velocity equatorial jets, hexagonal polar vortex, and complex ring-magnetosphere coupling.",
        supported_missions=["cassini"],
    ),
    "titan": BodyInfo(
        id="titan",
        name="Titan",
        category="moon",
        radius_km=2574.7,
        surface_gravity=1.352,
        mean_molecular_weight=28.6,  # 95% N2, 5% CH4
        gas_constant_r=290.7,
        isobaric_heat_capacity_cp=1040.0,
        reference_pressure_hpa=1467.0,  # 1.47 bar surface pressure
        atmospheric_composition={"N2": 95.0, "CH4": 4.9, "H2": 0.1},
        description="Largest moon of Saturn with dense nitrogen-methane atmosphere, organic photochemical haze, and liquid hydrocarbon seas.",
        supported_missions=["cassini"],
    ),
    "pluto": BodyInfo(
        id="pluto",
        name="Pluto",
        category="dwarf_planet",
        radius_km=1188.3,
        surface_gravity=0.62,
        mean_molecular_weight=28.01,  # >99% N2
        gas_constant_r=296.8,
        isobaric_heat_capacity_cp=1039.0,
        reference_pressure_hpa=0.0115,  # ~1.15 Pa (11.5 microbar) surface pressure
        atmospheric_composition={"N2": 99.0, "CH4": 0.5, "CO": 0.1},
        description="Kuiper belt dwarf planet with thin nitrogen atmosphere, extensive blue haze layers, and active nitrogen ice glaciers (Sputnik Planitia).",
        supported_missions=["new_horizons"],
    ),
    "mercury": BodyInfo(
        id="mercury",
        name="Mercury",
        category="terrestrial_planet",
        radius_km=2439.7,
        surface_gravity=3.7,
        mean_molecular_weight=20.0,
        gas_constant_r=415.7,
        isobaric_heat_capacity_cp=1000.0,
        reference_pressure_hpa=1e-12,
        atmospheric_composition={"O": 42.0, "Na": 29.0, "H": 22.0, "He": 6.0},
        description="Innermost planet with a dynamic surface-boundary exosphere, heavily cratered terrain, and extreme diurnal temperature swings.",
        supported_missions=["messenger", "bepicolombo"],
    ),
    "moon": BodyInfo(
        id="moon",
        name="Moon",
        category="moon",
        radius_km=1737.4,
        surface_gravity=1.62,
        mean_molecular_weight=20.0,
        gas_constant_r=415.7,
        isobaric_heat_capacity_cp=1000.0,
        reference_pressure_hpa=1e-11,
        atmospheric_composition={"He": 40.0, "Ne": 40.0, "Ar": 20.0},
        description="Planetary moon with surface-boundary exosphere, permanently shadowed polar craters with water ice, mapped by orbital radiometry and laser altimetry.",
        supported_missions=["lro"],
    ),
    "ceres": BodyInfo(
        id="ceres",
        name="Ceres",
        category="dwarf_planet",
        radius_km=469.7,
        surface_gravity=0.28,
        mean_molecular_weight=18.0,
        gas_constant_r=461.5,
        isobaric_heat_capacity_cp=1850.0,
        reference_pressure_hpa=1e-10,
        atmospheric_composition={"H2O": 99.0},
        description="Largest body in the asteroid belt with water-ice mantle, sodium carbonate bright deposits (Occator crater), and transient water vapor exosphere.",
        supported_missions=["dawn"],
    ),
    "vesta": BodyInfo(
        id="vesta",
        name="Vesta",
        category="asteroid",
        radius_km=262.7,
        surface_gravity=0.25,
        mean_molecular_weight=20.0,
        gas_constant_r=415.7,
        isobaric_heat_capacity_cp=1000.0,
        reference_pressure_hpa=0.0,
        atmospheric_composition={},
        description="Differentiated basaltic protoplanet in the asteroid belt with giant south polar impact basin Rheasilvia.",
        supported_missions=["dawn"],
    ),
    "comet_67p": BodyInfo(
        id="comet_67p",
        name="Comet 67P/C-G",
        category="comet",
        radius_km=2.0,
        surface_gravity=0.0001,
        mean_molecular_weight=18.0,
        gas_constant_r=461.5,
        isobaric_heat_capacity_cp=1850.0,
        reference_pressure_hpa=1e-8,
        atmospheric_composition={"H2O": 70.0, "CO": 15.0, "CO2": 10.0},
        description="Jupiter-family comet visited by Rosetta; active gas-and-dust coma, volatile sublimation jets, and organic compounds.",
        supported_missions=["rosetta"],
    ),
}


# ===========================================================================
# SPACECRAFT MISSIONS
# ===========================================================================

MISSIONS: Dict[str, MissionInfo] = {
    "akatsuki": MissionInfo(
        id="akatsuki",
        name="Akatsuki (VCO)",
        agency="JAXA / ISAS",
        launch_date="2010-05-20",
        mission_status="completed",
        primary_targets=["venus"],
        mission_type="orbiter",
        target_encounters={"venus": "orbiter"},
        instruments=[
            InstrumentInfo(id="RS", name="Radio Science Experiment", instrument_type="radio_science",
                           measurement_targets=["neutral_atmosphere"],
                           description="X-band radio occultation sounding Venus vertical temperature, pressure, refractivity, and static stability."),
            InstrumentInfo(id="UVI", name="Ultraviolet Imager", instrument_type="camera",
                           measurement_targets=["cloud_tops", "SO2"],
                           description="283 nm and 365 nm imaging tracking cloud-top wind vectors and SO2 distributions."),
            InstrumentInfo(id="LIR", name="Longwave Infrared Camera", instrument_type="camera",
                           measurement_targets=["cloud_tops", "thermal"],
                           description="10 micron uncooled microbolometer camera imaging cloud-top temperatures on day and night sides."),
            InstrumentInfo(id="IR1", name="1-Micron Camera", instrument_type="camera",
                           measurement_targets=["surface", "lower_clouds"],
                           description="Near-infrared camera imaging surface thermal emission and lower cloud dynamics."),
            InstrumentInfo(id="IR2", name="2-Micron Camera", instrument_type="camera",
                           measurement_targets=["middle_lower_clouds", "CO"],
                           description="Multi-band camera probing middle and lower clouds and carbon monoxide abundance."),
        ],
        authoritative_archive="JAXA DARTS / NASA PDS Atmospheres Node",
        archive_url="https://data.darts.isas.jaxa.jp/pub/pds3/",
        citation="Imamura, T., et al. (2017). Initial performance of the radio occultation experiment aboard Akatsuki. Earth, Planets and Space, 69(1), 137.",
        description="Japan's Venus Climate Orbiter dedicated to understanding the super-rotation and 3D dynamics of Venus' atmosphere.",
    ),
    "new_horizons": MissionInfo(
        id="new_horizons",
        name="New Horizons",
        agency="NASA / SwRI / JHUAPL",
        launch_date="2006-01-19",
        mission_status="operational",
        primary_targets=["pluto", "jupiter"],
        mission_type="flyby",
        target_encounters={"jupiter": "gravity_assist_flyby", "pluto": "flyby", "arrokoth": "flyby"},
        instruments=[
            InstrumentInfo(id="REX", name="Radio Science Experiment", instrument_type="radio_science",
                           measurement_targets=["neutral_atmosphere", "surface_pressure"],
                           description="Uplink radio occultation measuring Pluto's surface pressure, temperature profile, and ionosphere."),
            InstrumentInfo(id="LORRI", name="Long Range Reconnaissance Imager", instrument_type="camera",
                           measurement_targets=["surface", "haze"],
                           description="Panchromatic high-resolution visible telescope imaging Pluto, Charon, Arrokoth, and Kuiper belt objects."),
            InstrumentInfo(id="MVIC", name="Multispectral Visible Imaging Camera (Ralph)", instrument_type="camera",
                           measurement_targets=["surface", "color"],
                           description="4-color and panchromatic imaging camera mapping composition and color."),
            InstrumentInfo(id="SWAP", name="Solar Wind Around Pluto", instrument_type="plasma",
                           measurement_targets=["solar_wind", "plasma"],
                           description="Solar wind analyzer measuring interaction with Pluto's escaping atmosphere."),
            InstrumentInfo(id="PEPSSI", name="Pluto Energetic Particle Spectrometer Science Investigation", instrument_type="plasma",
                           measurement_targets=["energetic_particles"],
                           description="Measures energetic ions and electrons across the outer solar system."),
            InstrumentInfo(id="SDC", name="Venetia Burney Student Dust Counter", instrument_type="dust_counter",
                           measurement_targets=["interplanetary_dust"],
                           description="Measures mass and distribution of dust grains from 1 AU beyond 55 AU."),
        ],
        authoritative_archive="NASA PDS Atmospheres / Small Bodies / Ring-Moon Systems",
        archive_url="https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/Horizons/rex.html",
        citation="Stern, S. A., et al. (2015). The Pluto system: Initial results from its exploration by New Horizons. Science, 350(6258).",
        description="First mission to explore the Pluto-Charon system and the Kuiper Belt (Arrokoth), now exploring the outer heliosphere.",
    ),
    "juno": MissionInfo(
        id="juno",
        name="Juno",
        agency="NASA / JPL",
        launch_date="2011-08-05",
        mission_status="operational",
        primary_targets=["jupiter"],
        mission_type="orbiter",
        target_encounters={"jupiter": "orbiter"},
        instruments=[
            InstrumentInfo(id="GRAVITY_RO", name="Gravity & Radio Science", instrument_type="radio_science",
                           measurement_targets=["neutral_atmosphere", "gravity"],
                           description="Radio occultation and Doppler gravity sounding of Jupiter's deep atmosphere and core."),
            InstrumentInfo(id="MWR", name="Microwave Radiometer", instrument_type="spectrometer",
                           measurement_targets=["deep_atmosphere", "ammonia", "water"],
                           description="6-channel radiometer sounding from 1 bar down to >100 bars pressure."),
            InstrumentInfo(id="JIRAM", name="Jovian InfraRed Auroral Mapper", instrument_type="camera",
                           measurement_targets=["aurora", "hotspots"],
                           description="Infrared imager and spectrometer probing upper troposphere and auroral emissions."),
            InstrumentInfo(id="JunoCam", name="JunoCam Visible Imager", instrument_type="camera",
                           measurement_targets=["cloud_tops"],
                           description="Wide-angle color camera providing high-resolution views of polar cyclones and atmospheric bands."),
        ],
        authoritative_archive="NASA PDS Atmospheres Node",
        archive_url="https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/JUNO/juno.html",
        citation="Bolton, S. J., et al. (2017). Jupiter's interior and deep atmosphere: The initial results from the Juno mission. Science, 356(6340), 821-825.",
        description="Polar-orbiting spacecraft studying Jupiter's composition, gravity field, magnetic field, and polar magnetosphere.",
    ),
    "cassini": MissionInfo(
        id="cassini",
        name="Cassini-Huygens",
        agency="NASA / ESA / ASI",
        launch_date="1997-10-15",
        mission_status="completed",
        primary_targets=["saturn", "titan", "jupiter"],
        mission_type="orbiter",
        target_encounters={"jupiter": "gravity_assist_flyby", "saturn": "orbiter", "titan": "multiple_flybys"},
        instruments=[
            InstrumentInfo(id="RSS", name="Radio Science Subsystem", instrument_type="radio_science",
                           measurement_targets=["neutral_atmosphere", "rings", "ionosphere"],
                           description="S-, X-, and Ka-band occultation soundings of Saturn's and Titan's vertical atmospheres and ring particle sizes."),
            InstrumentInfo(id="CIRS", name="Composite Infrared Spectrometer", instrument_type="spectrometer",
                           measurement_targets=["thermal_structure", "composition"],
                           description="Thermal infrared spectrometer measuring vertical temperature profiles and trace gas abundances."),
            InstrumentInfo(id="ISS", name="Imaging Science Subsystem", instrument_type="camera",
                           measurement_targets=["surface", "clouds", "rings"],
                           description="Narrow and wide-angle cameras capturing multi-spectral images of Saturn, Titan, and icy moons."),
            InstrumentInfo(id="UVIS", name="Ultraviolet Imaging Spectrograph", instrument_type="spectrometer",
                           measurement_targets=["aurora", "haze"],
                           description="Probing atmospheric structure, auroras, and ring occultations in the far/extreme UV."),
        ],
        authoritative_archive="NASA PDS Atmospheres / Ring-Moon Systems",
        archive_url="https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/Cassini/cassini.html",
        citation="Matson, D. L., et al. (2002). Cassini/Huygens flyby of Jupiter. Science, 296(5571), 1281-1282.",
        description="Flagship orbiter of Saturn and Titan, yielding 13 years of revolutionary science including discovery of Enceladus plumes and Titan hydrocarbon lakes.",
    ),
    "vex": MissionInfo(
        id="vex",
        name="Venus Express (VEX)",
        agency="ESA",
        launch_date="2005-11-09",
        mission_status="completed",
        primary_targets=["venus"],
        mission_type="orbiter",
        target_encounters={"venus": "orbiter"},
        instruments=[
            InstrumentInfo(id="VeRa", name="Venus Radio Science Experiment", instrument_type="radio_science",
                           measurement_targets=["neutral_atmosphere", "ionosphere"],
                           description="Dual-frequency radio sounding of Venus vertical temperature from 40 to 90 km and day/night ionosphere."),
            InstrumentInfo(id="VMC", name="Venus Monitoring Camera", instrument_type="camera",
                           measurement_targets=["clouds", "airglow"],
                           description="Wide-angle camera imaging cloud dynamics in UV, visible, and near-IR."),
            InstrumentInfo(id="VIRTIS", name="Visible and Infrared Thermal Imaging Spectrometer", instrument_type="spectrometer",
                           measurement_targets=["surface_thermal", "cloud_composition"],
                           description="Spectrometer sounding lower atmosphere temperature through infrared atmospheric windows."),
        ],
        authoritative_archive="ESA Planetary Science Archive (PSA) / NASA PDS",
        archive_url="https://archives.esac.esa.int/psa/#!TableView/VEX=mission",
        citation="Tellmann, S., et al. (2009). The structure of Venus' middle atmosphere: Results from the Venus Express Radio Science experiment. JGR, 114.",
        description="ESA's first mission to Venus, providing 8 years of comprehensive atmospheric dynamics, chemistry, and cloud-layer profiling.",
    ),
    "maven": MissionInfo(
        id="maven",
        name="MAVEN",
        agency="NASA / GSFC / LASP",
        launch_date="2013-11-18",
        mission_status="operational",
        primary_targets=["mars"],
        mission_type="orbiter",
        target_encounters={"mars": "orbiter"},
        instruments=[
            InstrumentInfo(id="IUVS", name="Imaging Ultraviolet Spectrograph", instrument_type="spectrometer",
                           measurement_targets=["upper_atmosphere", "corona", "aurora"],
                           description="Measures global vertical profiles of neutral gases (CO2, CO, O) and ions in Mars' thermosphere and corona."),
            InstrumentInfo(id="NGIMS", name="Neutral Gas and Ion Mass Spectrometer", instrument_type="mass_spectrometer",
                           measurement_targets=["upper_atmosphere_composition"],
                           description="In-situ mass spectrometry measuring vertical isotopic and composition profiles during deep dips down to 125 km."),
            InstrumentInfo(id="ROSE", name="Radio Occultation Science Experiment", instrument_type="radio_science",
                           measurement_targets=["neutral_atmosphere", "ionosphere"],
                           description="Radio occultation soundings of Mars electron density profiles and neutral lower atmosphere."),
        ],
        authoritative_archive="NASA PDS Atmospheres Node",
        archive_url="https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/MAVEN/maven.html",
        citation="Jakosky, B. M., et al. (2015). MAVEN observations of the response of Mars to an interplanetary coronal mass ejection. Science, 350(6261).",
        description="Dedicated orbital mission exploring Mars upper atmosphere, ionosphere, and historical loss of volatile gases to space.",
    ),
    "bepicolombo": MissionInfo(
        id="bepicolombo",
        name="BepiColombo",
        agency="ESA / JAXA",
        launch_date="2018-10-20",
        mission_status="operational",
        primary_targets=["mercury", "venus"],
        mission_type="orbiter",
        target_encounters={"venus": "flyby", "mercury": "orbiter"},
        instruments=[
            InstrumentInfo(id="MORE", name="Mercury Orbiter Radio science Experiment", instrument_type="radio_science",
                           measurement_targets=["gravity", "occultation"],
                           description="High-precision radio science investigation during cruise flybys and Mercury orbit."),
            InstrumentInfo(id="MERTIS", name="Mercury Radiometer and Thermal Infrared Spectrometer", instrument_type="spectrometer",
                           measurement_targets=["surface", "thermal"],
                           description="Thermal infrared imaging spectrometer active during Venus flybys and Mercury science operations."),
            InstrumentInfo(id="PHEBUS", name="Probing of Hermean Exosphere By Ultraviolet Spectroscopy", instrument_type="spectrometer",
                           measurement_targets=["exosphere"],
                           description="UV spectrometer observing exospheric composition and emissions."),
        ],
        authoritative_archive="ESA Planetary Science Archive (PSA)",
        archive_url="https://archives.esac.esa.int/psa/",
        citation="Benkhoff, J., et al. (2010). BepiColombo—Comprehensive exploration of Mercury: Mission overview and science goals. PSS, 58(1), 2-20.",
        description="Joint European-Japanese mission to Mercury comprising MPO and MMO, performing multiple scientific flybys of Venus and Mercury on cruise.",
    ),
    "galileo": MissionInfo(
        id="galileo",
        name="Galileo",
        agency="NASA / JPL",
        launch_date="1989-10-18",
        mission_status="completed",
        primary_targets=["jupiter", "venus"],
        mission_type="orbiter",
        target_encounters={"venus": "flyby", "jupiter": "orbiter"},
        instruments=[
            InstrumentInfo(id="RSS", name="Radio Science", instrument_type="radio_science",
                           measurement_targets=["neutral_atmosphere", "ionosphere"],
                           description="S/X-band radio occultation measurements of Jupiter and Galilean moon ionospheres and atmospheres."),
            InstrumentInfo(id="SSI", name="Solid State Imaging", instrument_type="camera",
                           measurement_targets=["clouds", "moons"],
                           description="First CCD camera to orbit an outer planet, capturing dynamic atmospheric features and volcanism on Io."),
        ],
        authoritative_archive="NASA PDS Atmospheres Node / Imaging Node",
        archive_url="https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/catalog.htm#Jupiter",
        citation="Kliore, A. J., et al. (1997). The ionosphere of Europa from Galileo radio occultations. Science, 277(5324), 355-358.",
        description="Historic Jupiter orbiter that released an atmospheric probe and conducted first extensive radio occultations of Jovian moons.",
    ),
    "messenger": MissionInfo(
        id="messenger",
        name="MESSENGER",
        agency="NASA / JHUAPL",
        launch_date="2004-08-03",
        mission_status="completed",
        primary_targets=["mercury", "venus"],
        mission_type="orbiter",
        target_encounters={"venus": "flyby", "mercury": "orbiter"},
        instruments=[
            InstrumentInfo(id="RS", name="Radio Science Investigation", instrument_type="radio_science",
                           measurement_targets=["gravity", "exosphere"],
                           description="Doppler tracking and radio occultations characterizing Mercury's mass distribution and neutral exosphere."),
            InstrumentInfo(id="MDIS", name="Mercury Dual Imaging System", instrument_type="camera",
                           measurement_targets=["surface", "geology"],
                           description="Wide-angle and narrow-angle multispectral cameras mapping 100% of Mercury's surface."),
            InstrumentInfo(id="MASCS", name="Mercury Atmospheric and Surface Composition Spectrometer", instrument_type="spectrometer",
                           measurement_targets=["exosphere", "minerals"],
                           description="UV to near-IR spectrometer probing sodium, calcium, and magnesium exospheric emission tails."),
        ],
        authoritative_archive="NASA PDS Planetary Data System (Geosciences / PPI / Atmospheres)",
        archive_url="https://pds-geosciences.wustl.edu/missions/messenger/",
        citation="Solomon, S. C., et al. (2007). Return to Mercury: A global perspective on MESSENGER's first flyby. Science, 321(5885), 59-62.",
        description="First orbital mission around Mercury, confirming polar water-ice deposits, global volcanic plains, and dynamic exospheric cycling.",
    ),
    "magellan": MissionInfo(
        id="magellan",
        name="Magellan",
        agency="NASA / JPL",
        launch_date="1989-05-04",
        mission_status="completed",
        primary_targets=["venus"],
        mission_type="orbiter",
        target_encounters={"venus": "orbiter"},
        instruments=[
            InstrumentInfo(id="RADAR", name="Synthetic Aperture Radar & Altimeter", instrument_type="radar",
                           measurement_targets=["surface_topography"],
                           description="High-resolution S-band radar mapping 98% of Venus' cloud-shrouded surface at 100m resolution."),
            InstrumentInfo(id="GRS", name="Gravity & Radio Occultation Science", instrument_type="radio_science",
                           measurement_targets=["gravity_field", "neutral_atmosphere"],
                           description="X/S-band radio occultations of Venusian upper and middle atmospheric temperature and sulphuric acid vapor."),
        ],
        authoritative_archive="NASA PDS Magellan Node",
        archive_url="https://pds-geosciences.wustl.edu/missions/magellan/",
        citation="Saunders, R. S., et al. (1992). Magellan: Mission summary. JGR: Planets, 97(E8), 13067-13090.",
        description="Groundbreaking radar mapping mission revealing Venus' volcanically resurfaced landscape, impact craters, and coronae.",
    ),
    "pvo": MissionInfo(
        id="pvo",
        name="Pioneer Venus Orbiter (PVO)",
        agency="NASA / Ames",
        launch_date="1978-05-20",
        mission_status="completed",
        primary_targets=["venus"],
        mission_type="orbiter",
        target_encounters={"venus": "orbiter"},
        instruments=[
            InstrumentInfo(id="ORO", name="Orbiter Radio Occultation", instrument_type="radio_science",
                           measurement_targets=["neutral_atmosphere", "ionosphere"],
                           description="Seminal S/X-band radio occultations establishing the baseline thermal and ionospheric structure of Venus across solar cycles."),
            InstrumentInfo(id="ONMS", name="Orbiter Neutral Mass Spectrometer", instrument_type="mass_spectrometer",
                           measurement_targets=["thermosphere_composition"],
                           description="In-situ composition measurements in the Venusian upper atmosphere."),
        ],
        authoritative_archive="NASA PDS Atmospheres Node",
        archive_url="https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/PVO/pvo.html",
        citation="Colin, L. (1980). Pioneer Venus program. JGR: Space Physics, 85(A13), 7575-7598.",
        description="Operated in Venus orbit for over 14 years (1978-1992), measuring atmospheric structure and solar wind interactions through an entire solar cycle.",
    ),
    "lro": MissionInfo(
        id="lro",
        name="Lunar Reconnaissance Orbiter (LRO)",
        agency="NASA / GSFC",
        launch_date="2009-06-18",
        mission_status="operational",
        primary_targets=["moon"],
        mission_type="orbiter",
        target_encounters={"moon": "orbiter"},
        instruments=[
            InstrumentInfo(id="LROC", name="Lunar Reconnaissance Orbiter Camera", instrument_type="camera",
                           measurement_targets=["surface", "craters"],
                           description="Narrow Angle (0.5m/pixel) and Wide Angle (100m/pixel) camera imaging lunar terrain and landing sites."),
            InstrumentInfo(id="Diviner", name="Diviner Lunar Radiometer Experiment", instrument_type="radiometer",
                           measurement_targets=["surface_thermal", "water_ice"],
                           description="9-channel infrared radiometer measuring day/night surface thermal emissions and mapping ultra-cold polar cold traps down to 20 K."),
            InstrumentInfo(id="LAMP", name="Lyman Alpha Mapping Project", instrument_type="spectrometer",
                           measurement_targets=["polar_ice", "exosphere"],
                           description="Far-UV imaging spectrograph mapping permanently shadowed regions using starlight and interplanetary Lyman-alpha."),
        ],
        authoritative_archive="NASA PDS Geosciences / Imaging Nodes",
        archive_url="https://pds-geosciences.wustl.edu/missions/lro/",
        citation="Chin, G., et al. (2007). Lunar Reconnaissance Orbiter overview: The mission and its results. Space Sci Rev, 129(4), 391-419.",
        description="Comprehensive lunar mapping orbiter yielding ultra-high resolution topography, thermal atlases, and illumination models.",
    ),
    "mro": MissionInfo(
        id="mro",
        name="Mars Reconnaissance Orbiter (MRO)",
        agency="NASA / JPL",
        launch_date="2005-08-12",
        mission_status="operational",
        primary_targets=["mars"],
        mission_type="orbiter",
        target_encounters={"mars": "orbiter"},
        instruments=[
            InstrumentInfo(id="MCS", name="Mars Climate Sounder", instrument_type="radiometer",
                           measurement_targets=["atmospheric_temperature", "dust", "water_ice"],
                           description="Limb-sounding infrared radiometer profiling Martian temperature, dust opacity, and ice clouds from 0 to 80 km."),
            InstrumentInfo(id="HiRISE", name="High Resolution Imaging Science Experiment", instrument_type="camera",
                           measurement_targets=["surface", "active_processes"],
                           description="0.3m/pixel visible camera observing recurring slope lineae, avalanches, and polar ice caps."),
            InstrumentInfo(id="CRISM", name="Compact Reconnaissance Imaging Spectrometer for Mars", instrument_type="spectrometer",
                           measurement_targets=["surface_mineralogy"],
                           description="Visible and infrared imaging spectrometer identifying hydrated clay minerals and sulfates."),
        ],
        authoritative_archive="NASA PDS Geosciences / Atmospheres Nodes",
        archive_url="https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/MRO/mro.html",
        citation="Zurek, R. W., & Smrekar, S. E. (2007). An overview of the Mars Reconnaissance Orbiter (MRO) science investigation. JGR: Planets, 112(E5).",
        description="High-resolution reconnaissance orbiter providing ongoing daily climate soundings, atmospheric monitoring, and surface mapping of Mars.",
    ),
    "dawn": MissionInfo(
        id="dawn",
        name="Dawn",
        agency="NASA / JPL",
        launch_date="2007-09-27",
        mission_status="completed",
        primary_targets=["ceres", "vesta"],
        mission_type="orbiter",
        target_encounters={"mars": "gravity_assist_flyby", "vesta": "orbiter", "ceres": "orbiter"},
        instruments=[
            InstrumentInfo(id="FC", name="Framing Camera", instrument_type="camera",
                           measurement_targets=["surface_geology"],
                           description="Multispectral visible camera providing high-resolution stereoscopic terrain models of Vesta and Ceres."),
            InstrumentInfo(id="VIR", name="Visible and Infrared Spectrometer", instrument_type="spectrometer",
                           measurement_targets=["mineralogy", "ice_salts"],
                           description="Mapping surface mineralogy, ammoniated phyllosilicates, and sodium carbonate salt deposits."),
            InstrumentInfo(id="GRaND", name="Gamma Ray and Neutron Detector", instrument_type="spectrometer",
                           measurement_targets=["subsurface_composition", "hydrogen"],
                           description="Measuring elemental abundances of H, Fe, and K in the top meter of regolith."),
        ],
        authoritative_archive="NASA PDS Small Bodies Node",
        archive_url="https://pds-smallbodies.astro.umd.edu/data_sb/missions/dawn/",
        citation="Russell, C. T., & Raymond, C. A. (2011). The Dawn mission to Vesta and Ceres. Space Sci Rev, 163(1), 3-23.",
        description="Pioneering ion-propulsion mission: the first spacecraft to orbit two separate extraterrestrial destinations (Vesta and Ceres).",
    ),
    "rosetta": MissionInfo(
        id="rosetta",
        name="Rosetta",
        agency="ESA",
        launch_date="2004-03-02",
        mission_status="completed",
        primary_targets=["comet_67p"],
        mission_type="orbiter",
        target_encounters={"mars": "flyby", "comet_67p": "orbiter"},
        instruments=[
            InstrumentInfo(id="OSIRIS", name="Optical, Spectroscopic, and Infrared Remote Imaging System", instrument_type="camera",
                           measurement_targets=["nucleus", "coma_jets"],
                           description="Narrow and wide-angle imaging system tracking comet 67P activity, jets, and surface evolution."),
            InstrumentInfo(id="MIRO", name="Microwave Instrument for the Rosetta Orbiter", instrument_type="spectrometer",
                           measurement_targets=["subsurface_temperature", "coma_volatiles"],
                           description="Microwave radiometer and spectrometer measuring water, CO, and methanol outgassing rates and subsurface temperatures."),
            InstrumentInfo(id="RSI", name="Radio Science Investigation", instrument_type="radio_science",
                           measurement_targets=["gravity", "nucleus_mass", "coma"],
                           description="Doppler tracking and radio occultations determining comet mass, porosity, and gas coma density."),
        ],
        authoritative_archive="ESA Planetary Science Archive (PSA)",
        archive_url="https://archives.esac.esa.int/psa/#!TableView/Rosetta=mission",
        citation="Taylor, M. G., et al. (2017). The Rosetta mission orbital phase: Overview and science highlights. Phil. Trans. R. Soc. A, 375(2097).",
        description="First mission to rendezvous with and orbit a comet nucleus, accompanying 67P through perihelion and deploying Philae lander.",
    ),
}


# ===========================================================================
# HELPER FUNCTIONS
# ===========================================================================

def get_body(body_id: str) -> Optional[BodyInfo]:
    """Retrieve planetary body metadata."""
    return BODIES.get(body_id.lower())


def get_mission(mission_id: str) -> Optional[MissionInfo]:
    """Retrieve mission metadata."""
    return MISSIONS.get(mission_id.lower())


def list_bodies() -> List[dict]:
    """List all supported planetary bodies."""
    return [
        {
            "id": b.id,
            "name": b.name,
            "category": b.category,
            "radius_km": b.radius_km,
            "surface_gravity": b.surface_gravity,
            "mean_molecular_weight": b.mean_molecular_weight,
            "gas_constant_r": b.gas_constant_r,
            "isobaric_heat_capacity_cp": b.isobaric_heat_capacity_cp,
            "reference_pressure_hpa": b.reference_pressure_hpa,
            "atmospheric_composition": b.atmospheric_composition,
            "description": b.description,
            "supported_missions": b.supported_missions,
        }
        for b in BODIES.values()
    ]


def list_missions() -> List[dict]:
    """List all supported spacecraft missions with accurate classification."""
    return [
        {
            "id": m.id,
            "name": m.name,
            "agency": m.agency,
            "launch_date": m.launch_date,
            "mission_status": m.mission_status,
            "mission_type": m.mission_type,
            "primary_targets": m.primary_targets,
            "target_encounters": m.target_encounters,
            "authoritative_archive": m.authoritative_archive,
            "archive_url": m.archive_url,
            "citation": m.citation,
            "description": m.description,
            "instruments": [
                {
                    "id": i.id,
                    "name": i.name,
                    "type": i.instrument_type,
                    "targets": i.measurement_targets,
                    "description": i.description,
                }
                for i in m.instruments
            ],
        }
        for m in MISSIONS.values()
    ]


def get_missions_for_body(body_id: str) -> List[dict]:
    """Return all missions that observed a specific body with encounter classification."""
    body = get_body(body_id)
    if not body:
        return []
    res = []
    for mid in body.supported_missions:
        m = get_mission(mid)
        if m:
            encounter = m.target_encounters.get(body_id.lower(), m.mission_type)
            res.append({
                "id": m.id,
                "name": m.name,
                "agency": m.agency,
                "mission_type": m.mission_type,
                "encounter_type": encounter,
                "instruments": [i.name for i in m.instruments],
                "archive": m.authoritative_archive,
                "archive_url": m.archive_url,
            })
    return res
